In [1]:
import pandas as pd
import sys, os

sys.path.append(os.path.dirname(sys.path[0]))

In [2]:
reader = pd.read_csv(r'/home/gupessanha/Documentos/REPOS/SPSS/data/processed/neighbors.csv')

In [3]:
reader

,query_uid,query_name,query_role,aspect,metric,rank,neighbor_uid,neighbor_name,neighbor_role,score,score_kind
0,2002078863,Scott King,AM,T,Euclidiana,1,19399448,Matheus Régis,AM,1.377396,distance
1,2002078863,Scott King,AM,T,Euclidiana,2,2002075081,Ricardo Cervantes,AM,1.378118,distance
2,2002078863,Scott King,AM,T,Euclidiana,3,31042062,Abraham Odoh,MID,1.539899,distance
3,2002078863,Scott King,AM,T,Euclidiana,4,2002078072,George Smith,AM,1.579829,distance
4,2002078863,Scott King,AM,T,Euclidiana,5,70109065,Fıratcan Üzüm,MID,1.649326,distance
...,...,...,...,...,...,...,...,...,...,...,...
9393955,37001809,Jordy Clasie,DEF,SP,Pearson,6,55063818,Pipas,MID,0.999914,similarity
9393956,37001809,Jordy Clasie,DEF,SP,Pearson,7,28127116,Tyler Onyango,DM,0.999866,similarity
9393957,37001809,Jordy Clasie,DEF,SP,Pearson,8,43190957,Antonio D'Alena,DM,0.999866,similarity
9393958,37001809,Jordy Clasie,DEF,SP,Pearson,9,2000062196,Tenner,DM,0.999866,similarity
9393959,37001809,Jordy Clasie,DEF,SP,Pearson,10,16061334,Manuel Prietl,DM,0.999866,similarity

In [4]:
neymar = reader.loc[reader['query_name']== 'Neymar']

In [5]:
neymar

,query_uid,query_name,query_role,aspect,metric,rank,neighbor_uid,neighbor_name,neighbor_role,score,score_kind
503570,19024412,Neymar,MID,T,Euclidiana,1,862068,Haris Medunjanin,DM,1.650114,distance
503571,19024412,Neymar,MID,T,Euclidiana,2,8430773,Jérémy Ménez,AM,1.806950,distance
503572,19024412,Neymar,MID,T,Euclidiana,3,14044150,Paulo Dybala,AM,1.836613,distance
503573,19024412,Neymar,MID,T,Euclidiana,4,8832853,Marcelo,DEF,1.943207,distance
503574,19024412,Neymar,MID,T,Euclidiana,5,85139014,Kylian Mbappé,AM,1.990651,distance
...,...,...,...,...,...,...,...,...,...,...,...
9114705,19024412,Neymar,MID,SP,Pearson,6,29023466,James Rowe,DM,0.999796,similarity
9114706,19024412,Neymar,MID,SP,Pearson,7,43039014,Felipe,DM,0.999796,similarity
9114707,19024412,Neymar,MID,SP,Pearson,8,25034173,Lukáš Masopust,DEF,0.999787,similarity
9114708,19024412,Neymar,MID,SP,Pearson,9,19028050,Thiago Carleto,DEF,0.999629,similarity
9114709,19024412,Neymar,MID,SP,Pearson,10,76017992,Jhony Cano,AM,0.999618,similarity